### ISSUE TITLE
Peerreview notebook W6_15

### ISSUE THREAD

**Issue by StijnMichiels00** [maartenmarx/KD2021#2]
Bij het reviewen van de notebook W6_15 (https://github.com/maartenmarx/KD2021/blob/master/W5/W6_15.ipynb) moet de notebook worden gerunt om de volledigheid van de notebook te kunnen zien. In de github viewer verschijnen er geen dropdown menu's bij de output van de rdf database en de gemaakte queries. Hierdoor is de notebook niet volledig weergegeven in de github viewer.

**Comment by maartenmarx** [comment]
@StijnMichiels00 dan download je hem toch? Of je cloned de hele repo. Nog makkelijker.

**Comment by StijnMichiels00** [comment]
Ja klopt dat zou ik mensen ook willen aanraden als ze mijn notebook peerreviewen. Ik heb deze notebook gemaakt en wilde mensen graag informeren voor over het reviewen van mijn notebook
